# For more information, please see https://pixi.prefix.dev/dev/reference/pixi_manifest/

[workspace]
authors = ["Alex Maldonado <alex.maldonado@pitt.edu>"] # TODO: Add to group members before Alex
channels = ["conda-forge", "bioconda", "nvidia", "pytorch"]
name = "biosc1640-project"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "26.2.10"

[system-requirements]
linux = "4.18"
libc = { family = "glibc", version = "2.28" }
macos = "13.0"

[environments]
dev = ["dev"]

[tasks]

[dependencies]
python = ">=3.12.0,<3.15"
loguru = ">=0.7.3,<1.0"

[feature.dev.dependencies]
ruff = ">=0.15.0,<0.18"
setuptools = ">=82.0.0,<83"
setuptools-scm = ">=9.2.2,<10"
wheel = ">=0.46.3,<0.47"

[feature.dev.tasks]
format = { cmd = ["ruff", "check", "--select", "I", "--fix", "&&", "ruff", "format", "--config", ".ruff.toml", "./"] }
